version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nttp-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - nttp-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  producer:
    env_file: .env
    build:
      context: ./
      dockerfile: ./backend/producer/dockerfile
    container_name: producer
    depends_on:
      - kafka
    networks:
      - nttp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  consumer:
    env_file: .env
    build:
      context: ./
      dockerfile: ./backend/consumer/dockerfile
    container_name: consumer
    depends_on:
      - kafka
    networks:
      - nttp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  nttp-network:
    driver: bridge
