# Base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy root-level package files for dependency installation
COPY package.json /app

# Install dependencies
RUN npm install

# Copy the producer script after dependencies are installed
COPY backend/producer/producer.mjs .

# Expose necessary port (if any, e.g., for Kafka)
EXPOSE 9092

# Run the producer script
CMD ["node", "producer.mjs"]
